sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mohankumar19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mohankumar19/docker-react npm run test